token:
  expire.interval: 1800 #time after which tokens expire, in seconds

server:
  port : 8081

spring:
  profiles.actives: test
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/bank?useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties.mail.smtp:
      starttls.enable: true
      starttls.required: true
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000